# Generated by Django 5.2.6 on 2025-09-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
