# Generated by Django 5.2.6 on 2025-09-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='likes',
        ),
        migrations.AddField(
            model_name='todo',
            name='liked_by',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
